import Menu from "./componentes/Menu";
import Macarrao from "./componentes/Macarrao";
import 'bootstrap/dist/css/bootstrap.min.css';

export const metadata = {
  title: 'Aulas PTAC',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body>
        
        <Menu/>
        <Macarrao/>
        

        {children}
        </body>
    </html>
  );
}
